apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-applicationset
  namespace: argocd
spec:
  generators:
    - list:
      elements:
        - namespace: cq
        - namespace: tst
        - namespace: prd
  template:
    metadata:
      name: '{{"{{"}}namespace{{"}}"}}-poc-app'
    spec:
      project: default
      source:
#        helm:
#          # specify different values file based on directories variables
#          valueFiles:
#            - "demo/configs/tst/values.yaml"
##            - "configs/{{path[2]}}/values.yaml"
        path: demo
        repoURL: https://github.com/Emc285/argocd-helm-demo.git
        targetRevision: HEAD
        releaseName: poc-app
        valueFiles:
#          - values.yaml
          - configs/tst/values.yaml
      destination:
        # default cluster as destination, you can define multiple clusters in ArgoCD UI
        server: https://kubernetes.default.svc
        # will deploy to different namespaces as different destinations
        namespace: '{{"{{"}}namespace{{"}}"}}'
