apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: example
spec:
  generators:
    - list:
        elements:
          - namespace: tst
            name: demo-applicationset-values
          - namespace: cq
            name: demo-applicationset-values
          - namespace: prd
            name: demo-applicationset-values
  template:
    metadata:
      name: '{{name}}-example'
    spec:
      project: default
      source:
        repoURL: https://github.com/Emc285/demo-applicationset-values.git
        targetRevision: main
        path: demo
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'