apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: poc-app
spec:
  generators:
    - list:
        elements:
          - namespace: tst
          - namespace: cq
          - namespace: prd
  template:
    metadata:
      name: '{{"{{"}}namespace{{"}}"}}-poc-app'
    spec:
      project: default
      source:
        path: config
        repoURL: https://github.com/Emc285/argocd-helm-demo.git
        targetRevision: HEAD
        helm:
          releaseName: poc-app
          valueFiles:
            - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{"{{"}}namespace{{"}}"}}'