apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo-applicationset
  namespace: argocd
spec:
  generators:
    - list:
      elements:
        - namespace: cq
        - namespace: tst
        - namespace: prd
  template:
    metadata:
      name: '{{"{{"}}namespace{{"}}"}}-poc-app'
    spec:
      project: default
      source:
#          # specify different values file based on directories variables
#          valueFiles:
#            - "demo/configs/tst/valuestst.yaml"
##            - "configs/{{path[2]}}/valuestst.yaml"
        path: demo
        repoURL: https://github.com/Emc285/argocd-helm-demo.git
        targetRevision: HEAD
        helm:
          valueFiles:
            - values.yaml
          values: |-
            {{values}}
      destination:
        # default cluster as destination, you can define multiple clusters in ArgoCD UI
        server: https://kubernetes.default.svc
        # will deploy to different namespaces as different destinations
        namespace: tst
