apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: poc-app
spec:
  generators:
    - list:
        elements:
#          - namespace: tst
          - namespace: cq
#          - namespace: prd
#            url: https://kubernetes.default.svc
  template:
    metadata:
      name: poc-app
    spec:
      project: default
      source:
        path: demo
        repoURL: https://github.com/Emc285/argocd-helm-demo.git
        targetRevision: main
        helm:
          releaseName: poc-app
          valueFiles:
            - valuesxyz.yaml
            - values-cq.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: tst