apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: poc-app
spec:
  generators:
    - list:
        elements:
          - namespace: tst
            url: https://kubernetes.default.svc
          - namespace: cq
            url: https://kubernetes.default.svc
          - namespace: prd
            url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{"{{"}}namespace{{"}}"}}-poc-app'
    spec:
      project: default
      source:
        path: demo
        repoURL: https://github.com/Emc285/argocd-helm-demo.git
        targetRevision: HEAD
        helm:
          releaseName: poc-app
          valueFiles:
            - valuesxyz.yaml
            - values-{{"{{"}}namespace{{"}}"}}.yaml
      destination:
        server: '{{"{{"}}url{{"}}"}}'
        namespace: '{{"{{"}}namespace{{"}}"}}'