apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: demo
  namespace: argocd
spec:
  generators:
    - list:
    - git:
        repoURL: https://github.com/Emc285/argocd-helm-demo.git
        revision: HEAD
        directories:
          # here it will read the paths under configs and the subpaths under the config paths
          - path: configs/tst
  template:
    metadata:
      namespace: argocd
      # you can use the path strings with / delimiter as variables
      name: "{{path[2]}}-{{path.basename}}"
    spec:
      project: default
      source:
        helm:
          # specify different values file based on directories variables
          valueFiles:
            - "demo/configs/tst/values.yaml"
#            - "configs/{{path[2]}}/values.yaml"
        path: demo/configs/tst
        repoURL: https://github.com/Emc285/argocd-helm-demo.git
        targetRevision: HEAD
      destination:
        # default cluster as destination, you can define multiple clusters in ArgoCD UI
        server: https://kubernetes.default.svc
        # will deploy to different namespaces as different destinations
        namespace: '{{path.basename}}'
