apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argotest
spec:
  generators:
    - list:
        elements:
          - namespace: tst
          - namespace: cq
          - namespace: prd
  template:
    metadata:
      name: '{{namespace}}-argocd-helm'
    spec:
      project: default
      source:
        path: 'configs/{{namespace}}'
        repoURL: https://github.com/Emc285/argocd-helm-demo.git
        targetRevision: HEAD
        helm:
          releaseName: argotest
          valueFiles:
            - values.yaml
            - configs/tst/values.yaml
            - configs/prd/values.yaml
            - configs/cq/values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'