apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sample-app.fullname" . }}
  labels:
  {{- include "sample-app.labels" . | nindent 4 }}
data:
  settings.ini: |
    # possible values : prd, cq, tst
    app_mode = {{ .Values.appMode }}
    [security]
    # Path to SSL certificates
    certificates = {{ .Values.certificatePath }}
    [paypal]
    paypal_url = {{ .Values.paypalURLLocation }}
    [mysql]
    db_user = {{ .Values.databaseUser }}
    db_password = {{ .Values.databasePassword }}