# Default values for sample-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

name: cq

image:
  repository: amralaayassen/helm-app
  pullPolicy: IfNotPresent
#  # Overrides the image tag whose default is the chart appVersion.
#  tag: "cq"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 30007

tag:
  versãoServiço:

## Application level settings  
appMode: cq
certificatePath: /etc/ssl/cq
paypalURLLocation: https://cq.paypal.example.com
databaseUser: cq-user
databasePassword: cq-password




