# Default values for sample-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

name: tst

image:
  repository: amralaayassen/helm-app
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
#  tag: "tst"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 30008


## Application level settings
appMode: tst
certificatePath: /etc/ssl/tst
paypalURLLocation: https://tst.paypal.example.com
databaseUser: tst-user
databasePassword: tst-password




